// Response banks for synthetic learners. Each category is something a real
// Tamil-speaking learner plausibly types; the simulator picks from them by latent cause.
export const BANK = {
  'past-go': {
    correct: ['Yesterday evening, I went to the market.', 'I watched a movie with my family.', 'Yesterday I played cricket with my friends.', 'I went to the temple and ate dinner.', 'yesterday i studied for my exam', 'Last Sunday I visited my grandmother.'],
    knowledge: ['Yesterday I go to the market.', 'I eat dinner and watch TV.', 'Yesterday I play cricket.', 'Yesterday I goed to the shop.'],
    transfer: ['Yesterday I market went.', 'I temple went with family.'],
    codeswitch: ['Yesterday I santhai ponen', 'nethu naan kovil ponen', 'I friend kooda padam parthen', 'yesterday I saapten and padichen'],
    fragments: ['I... um... yesterday I...', 'yesterday... market... I', 'I go... no... I...', 'I... I...'],
    offtopic: ['My name is Priya.', 'Tomorrow is holiday.'],
    guidedCorrect: ['went to the market', 'watched TV with my family', 'ate idli and slept'],
    guidedWrong: ['go to the market', 'market going', 'eat dinner'],
  },
  articles: {
    correct: ['There is an apple on the table.', 'An apple is on the table.', 'there is an apple on the kitchen table', 'There is an orange on the chair.'],
    knowledge: ['There is a apple on the table.', 'There is a orange on the chair.'],
    transfer: ['There is apple on the table.', 'There is one apple on the table.', 'Apple is there on table.'],
    codeswitch: ['mesai mela oru apple irukku', 'There is apple table mela', 'oru apple irukku'],
    fragments: ['There is... um... apple...', 'apple... table'],
    offtopic: ['I like fruits.', 'My mother bought it.'],
    guidedCorrect: ['an'], guidedWrong: ['a', 'one'],
  },
  prepositions: {
    correct: ['At night, I keep my phone on the table.', 'I keep my phone under my pillow.', 'i keep it in my bag', 'I keep my phone near the bed.'],
    knowledge: ['I keep my phone at the table.', 'I keep my phone in table.'],
    transfer: ['I keep my phone table on.', 'I keep phone table', 'I keep my phone table-la'],
    codeswitch: ['I keep phone table mela', 'thalaiyanai keezha vaipen', 'phone pai ulla'],
    fragments: ['I keep... um... phone...', 'at night... phone... the'],
    offtopic: ['I sleep at 11 o clock.', 'My phone is Samsung.'],
    guidedCorrect: ['on the table', 'under my pillow', 'in my bag'], guidedWrong: ['table on', 'in table', 'table-la'],
  },
  advice: {
    correct: ['You should take your medicine and rest.', 'You should see a doctor.', 'Take rest and drink hot water.', 'get well soon, take some rest'],
    knowledge: ['You must to go hospital.', 'You are sick.'],
    transfer: ['You should eat medicine and rest.', 'Go and see doctor.'],
    codeswitch: ['You should marundhu saapdu', 'marunthu sapdu, oyvu edu', 'You should doctor-a paaru, thanni kudi'],
    fragments: ['You... um... should...', 'medicine... um... you'],
    offtopic: ['My friend lives in Trichy.', 'I am fine.'],
    guidedCorrect: ['take medicine and rest', 'see a doctor', 'drink hot water and sleep'], guidedWrong: ['eat medicine', 'medicine take', 'doctor see'],
  },
  questions: {
    correct: ['Where do you live?', 'where do you stay', 'Where is your house?', 'Where do you work?'],
    knowledge: ['Where are you live?', 'Where does you live?'],
    transfer: ['Where you live?', 'You live where?', 'You where live?'],
    codeswitch: ['Neenga enga irukeenga?', 'Where you irukeenga?'],
    fragments: ['Where... um... you...', 'you... live...'],
    offtopic: ['I live in Chennai.', 'My house is big.'],
    guidedCorrect: ['do'], guidedWrong: ['are', 'does'],
  },
  'third-person': {
    correct: ['Every morning, my mother makes coffee.', 'My father reads the newspaper.', 'She cooks breakfast for us.', 'My dad goes for a walk.'],
    knowledge: ['My mother make coffee.', 'My father read the newspaper.', 'He go to office.'],
    transfer: ['My father, they go to office.', 'My mother are cooking.'],
    codeswitch: ['Amma kaapi poduvanga', 'My father paper padippar'],
    fragments: ['My mother... um... she...', 'every morning... coffee...'],
    offtopic: ['I wake up at 6.', 'I drink tea.'],
    guidedCorrect: ['makes coffee', 'cooks breakfast', 'prays in the pooja room'], guidedWrong: ['make coffee', 'cook breakfast'],
  },
  continuous: {
    correct: ['Right now, I am learning English.', "I'm practising English on my laptop.", 'I am sitting in my room.'],
    knowledge: ['I learning English.', 'I learn English now.', 'I am learn English.'],
    transfer: ['English learning I am.'],
    codeswitch: ['Naan English kathukittu irukken', 'I am padichitu'],
    fragments: ['I... um... English...', 'now... I am...'],
    offtopic: ['I like English.', 'Yes.'],
    guidedCorrect: ['learning English', 'studying', 'talking to you'], guidedWrong: ['learn English', 'study'],
  },
  comparative: {
    correct: ['Ooty is colder than Chennai.', 'Chennai is hotter than Ooty.', 'Ooty is cooler than Chennai.', 'A bike is faster than a bus.'],
    knowledge: ['Ooty is more cold than Chennai.', 'Ooty is cold, Chennai is hot.'],
    transfer: ['Chennai than Ooty is cold.', 'Chennai than Ooty cold.'],
    codeswitch: ['Chennai-ai vida Ooty kulir', 'Ooty is more kulir than Chennai'],
    fragments: ['Ooty... um... cold...', 'Chennai... hot... more'],
    offtopic: ['I went to Ooty last year.', 'I like Chennai.'],
    guidedCorrect: ['colder', 'cooler'], guidedWrong: ['more cold', 'cold'],
  },
};

export const HEDGES = {
  dontUnderstand: ['puriyala', "sorry, I don't understand", 'meaning?', 'enna artham?', 'what?'],
  dontKnow: ["I don't know", 'theriyala', 'no idea'],
  cantSay: ['I know but solla theriyala', 'how to say in English?', 'solla theriyala'],
  forgot: ['I forgot the word', 'marandhuten', 'it is on the tip of my tongue'],
};
